# Generated by Django 4.2.4 on 2023-09-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=50)),
                ("Prénom", models.CharField(max_length=50)),
                ("Adresse", models.CharField(max_length=150)),
                ("Téléphone", models.IntegerField(max_length=20)),
                ("Email", models.CharField(max_length=150)),
                ("Mot De Passe", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=50)),
                ("Prix", models.IntegerField(max_length=20)),
                ("Description", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantité", models.IntegerField(max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCommerce.client",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCommerce.produit",
                    ),
                ),
            ],
        ),
    ]
