# Generated by Django 4.2.4 on 2023-09-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CIN", models.IntegerField()),
                ("Nom", models.CharField(max_length=50)),
                ("Prenom", models.CharField(max_length=50)),
                ("Adresse", models.CharField(max_length=150)),
                ("Telephone", models.IntegerField()),
                ("Email", models.CharField(max_length=150)),
                ("MotDePasse", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=50)),
                ("Prix", models.FloatField(default=0.0)),
                ("Description", models.TextField(blank=True)),
                (
                    "Image",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0)),
                ("date_commande", models.DateTimeField(blank=True, null=True)),
                (
                    "type_facture",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu"),
                            ("facture_proforma", "Facture Proforma"),
                            ("facture", "Facture"),
                        ],
                        default="reçu",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCommerce.client",
                    ),
                ),
                ("produit", models.ManyToManyField(to="gestionCommerce.produit")),
            ],
        ),
    ]
