# Generated by Django 4.2.4 on 2023-09-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="produit",
        ),
        migrations.CreateModel(
            name="CommandeProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantite", models.PositiveIntegerField(default=1)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCommerce.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCommerce.produit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commande",
            name="produits",
            field=models.ManyToManyField(
                through="gestionCommerce.CommandeProduit", to="gestionCommerce.produit"
            ),
        ),
    ]
