# Generated by Django 4.2.4 on 2023-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Téléphone",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="commande",
            name="Quantité",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="produit",
            name="Prix",
            field=models.IntegerField(),
        ),
    ]
