# Generated by Django 4.2.4 on 2023-09-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionCommerce",
            "0002_alter_client_téléphone_alter_commande_quantité_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="Mot De Passe",
            new_name="MotDePasse",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="Prénom",
            new_name="Prenom",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="Téléphone",
            new_name="Telephone",
        ),
    ]
