# Generated by Django 4.2.4 on 2023-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0002_remove_commande_produit_commandeproduit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateField(blank=True, null=True),
        ),
    ]
