# Generated by Django 4.2.4 on 2023-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0003_alter_commande_date_commande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
