# Generated by Django 4.2.4 on 2023-09-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0004_alter_commande_date_commande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandeproduit",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionCommerce.produit",
            ),
        ),
    ]
