# Generated by Django 4.2.4 on 2023-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0004_produit_image_produit_quantite_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="Quantité",
            new_name="Quantite",
        ),
        migrations.AddField(
            model_name="commande",
            name="date_commande",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="commande",
            name="produit",
        ),
        migrations.AddField(
            model_name="commande",
            name="produit",
            field=models.ManyToManyField(to="gestionCommerce.produit"),
        ),
    ]
