# Generated by Django 4.2.4 on 2023-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCommerce", "0005_rename_quantité_commande_quantite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="CIN",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
